"%dev":
  quarkus:
    spring-cloud-config:
      enabled: false
    application:
      name: test-ms
      version: 1.0.0
    http:
      port: 9091
      auth:
        basic: false
      cors: true
      root-path: /
    cxf:
      path: /soap
    resteasy:
      path: /api
    log:
      level: INFO
      console:
        enable: true
        format: "%d ${LOG_LEVEL_PATTERN:-%5p} [%c{2.}] | %m%n"
        level: DEBUG
        color: false
    package:
      type: fast-jar
    profile: svil
    smallrye-health:
      root-path: /api/health
      liveness-path: /api/health/live
    smallrye-openapi:
      path: /api/openapi
    test:
      native-image-profile: svil
      profile: test
    vertx:
      max-event-loop-execute-time: 60S
      warning-exception-time: 60S
  kafka:
    bootstrap:
      servers: td-kafka01-s1:9092,td-kafka02-s1:9092,td-kafka03-s1:9092
      health:
        enabled: true
    devservices:
      enabled: false
  mp:
    messaging:
      incoming:
        event:
          connector: smallrye-kafka
          auto:
            offset:
              reset: earliest
          topic: TEST_ASINC_LOCAL
          group:
            id: my-group
          partitions: 3
          value:
            deserializer: org.acme.api.ResourceDeserializeDTO
      outgoing:
        sender:
          connector: smallrye-kafka
          topic: TEST_ASINC_LOCAL
          value:
            serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer